### ISSUE TITLE
Drag more audio file types

### ISSUE THREAD

**Issue by zimm44** [cswendrowski/FoundryVTT-Drag-Upload#1]
First of all, this is an amazing mod, thank you!

I suggest that this mod allows us to drag and drop more audio files, for example OGG is widely used for small audio files.

**Comment by cswendrowski** [comment]
@zimm44 any other audio formats I'm missing while I'm at it?

**Comment by zimm44** [comment]
The most critical I think is OGG as the huge 4 audio packs are in that format, but I'd suggest the most common ones, specially compressed like WMA and AAC

**Comment by shawndibble** [comment]
Webm for images isn't working either

**Comment by cswendrowski** [comment]
I appreciate those lists, and will use them!

WEBM isn't allowed as an Image under that list FYI

**Comment by shawndibble** [comment]
There is also VIDEO_FILE_EXTENSIONS as well.

**Comment by cswendrowski** [comment]
Closed as of v1.1.0
