### ISSUE TITLE
[sfrpg] Drag-Upload trying to upload items that were dragged from the item menu

### ISSUE THREAD

**Issue by supernovajm** [cswendrowski/FoundryVTT-Drag-Upload#12]
In SFRPG system, items can be dragged from the sidebar and be placed on the map as if they were actors. Drag-Upload is capturing these events and trying to upload the image

expected behavior: Items dragged from the item menu should be ignored by drag-upload, just like actors are.

**Comment by cswendrowski** [comment]
Fixed in v1.5.2
