### ISSUE TITLE
access unauthorized. please enter your api key or sign into The Forge" error message

### ISSUE THREAD

**Issue by gregoryfl** [cswendrowski/FoundryVTT-Drag-Upload#13]
Mod appears to cause the following error message to appear when players join game in Forge..."access unauthorized. please enter your api key or sign into The Forge" When mod is disabled, there is no error message.

**Comment by 736dave** [comment]
We had the same issue Wednesday night.  Same resolution, disabling mods until it worked (Drag Upload).  thanks

**Comment by cswendrowski** [comment]
Fixed in v1.5.2
