### ISSUE TITLE
Drag Upload 1.5.2 introduce duplicated tokens on drop from Actor Tab.

### ISSUE THREAD

**Issue by intemptesta** [cswendrowski/FoundryVTT-Drag-Upload#14]
Drag Upload 1.5.2
Foundry 0.7.7
DnD5e 1.1.1

Whenever I drop an actor from Actor Tab to Scene, there are two duplicate tokens on the point I dropped, stacked together.
AFAIK this doesn't happen on Drag Upload 1.5.1.

**Comment by caerandir** [comment]
Have the same issue with 0.7.8.

**Comment by reubzilla** [comment]
I too have experienced the same issue, 0.7.8 previously it worked fine on 0.7.7

**Comment by kquinby** [comment]
Also affects tile placements. 0.7.8

**Comment by Pipizio** [comment]
Idem

**Comment by jacobjorvang** [comment]
Tried commenting out the four new `canvas._dragDrop.callbacks.drop(event);` lines and this fixes the issue. Since I don't see any of the text strings for the first three cases in the console, I think it's line 95 that's causing the problem.

**Comment by cswendrowski** [comment]
Fixed in 1.5.3, thanks for the reports!
