### ISSUE TITLE
[Feature Request] Upload token image to opened character sheet.

### ISSUE THREAD

**Issue by dmrickey** [cswendrowski/FoundryVTT-Drag-Upload#16]
I've got compendiums filled with actors already. What would be awesome is if I could drag one of those Actors in from the compendium, then open up its character sheet, then drag an image from my desktop over the Actor's token image and have it upload as the token for the already-existing Actor.

**Comment by cswendrowski** [comment]
Hey there @dmrickey, thanks for the suggestion!

Unfortunately, each sheet stores images in a possibly different location, and a sheet can have more than one image on it. Drag Upload would likely need per-system support for each of the sheets, which isn't something I'm looking to add

You could try your hand with the Compendium Image Mapper module: https://foundryvtt.com/packages/imagemapper/

**Comment by dmrickey** [comment]
Can you target the specific element that's hovered? If there was metadata on the image that exposed its path would that be something that could be integrated with?
