### ISSUE TITLE
Multiple uploads

### ISSUE THREAD

**Issue by Mordecaine** [cswendrowski/FoundryVTT-Drag-Upload#21]
Hello,

first of all; I really enjoy your module.

But if I have a lot of NPCs or Characters, it is a bit exhausting to upload every picture by its own.
So maybe it is possible to add a feature, where you can upload a lot of pictures at once.

**For example:**
You Drag and Drop two or more pictures to Foundry. After that, a table with all picture names (or maybe a thumbnail of all pictures) shows up. In this table I'm now able to define for every single picture, whether it is a NPC or a character or whatever.

**Comment by cswendrowski** [comment]
Not something I plan on adding, sorry
