### ISSUE TITLE
Drag upload no longer working

### ISSUE THREAD

**Issue by gogrady4117** [cswendrowski/FoundryVTT-Drag-Upload#26]
Attempting to drag images from data folder into foundry no longer working. Running in administration mode with only module Drag Upload enabled.

**Comment by cswendrowski** [comment]
You should run Foundry in *non* admin mode: https://github.com/cswendrowski/FoundryVTT-Drag-Upload#warning---drag-upload-will-not-work-if-you-run-foundry-in-admin-mode-on-windows-due-to-a-windows-security-feature
