### ISSUE TITLE
PF2E spell effects can't be dragged onto tokens while Drag Upload is enabled

### ISSUE THREAD

**Issue by laurieathey** [cswendrowski/FoundryVTT-Drag-Upload#30]
Hey,

Not sure if this will affect other systems but in the PF2E system the mod is doing something weird.

The system has "spell effects", essentially objects you drag from chat onto a token, and it applies the effects of the spell: EG An increase to speed, or adding a bonus to attack rolls, etc.

The effect appears as a draggable item in the chat, and upon release the logs show the following:
![image](https://user-images.githubusercontent.com/11553364/121228134-a9856380-c88c-11eb-938c-f8c6284cfb80.png)

Text version for easier debugging
```
Uncaught (in promise) ReferenceError: IMAGE_FILE_EXTENSIONS is not defined
    at handleDrop (dragupload.js:71)
    at DragDrop.callback (foundry.js:20730)
    at DragDrop._handleDrop (foundry.js:20781)
```
I suspect eh second console log is the reason:
```
FileList {length: 0}
length: 0
__proto__: FileList
```
Presumably it's crashing the event handling by not handling the filelist being empty and the other event handlers never get called so the effect never gets set to the sheet.
If you wanna test this: Latest Foundry version (0.8.6)
Latest PF system: 2.1.1.6025
![image](https://user-images.githubusercontent.com/11553364/121228444-0d0f9100-c88d-11eb-97e3-1aa2b6a262d9.png)

Make a token (player/npc doesn't matter) and get the spell Longstrider to appear in chat. Add it to a character is probably the easiest way and click the icon of the spell (turns into adice) to post it to chat.
From there drag the Spell Effect: Longstrider item onto the token and watch the logs.
Without this mod it's fine.
With the mod the above errors occur.

**Comment by laurieathey** [comment]
V2.0 of the mod seems to have resolved this. 
Good job :)

**Comment by cswendrowski** [comment]
> 
> 
> V2.0 of the mod seems to have resolved this.
> Good job :)

I did nothing to fix this, but I'll take it! Thanks for reporting
