### ISSUE TITLE
No Effect

### ISSUE THREAD

**Issue by Nuku** [cswendrowski/FoundryVTT-Drag-Upload#4]
Trying to drag various images towards Foundry does not allow me to import them. Letting go of the button just ends the drag and nothing else. The module is confirmed active on the list.

**Comment by fellowhoodlum** [comment]
Same here. Having no such luck. Running 0.6.5.

**Comment by cswendrowski** [comment]
@Nuku with help from the community, we have finally tracked this down - please do **not** run Foundry in admin mode - Windows blocks dragging files as a security feature when running the program as admin.
