### ISSUE TITLE
Download in Version 2.2.1 is still pointing to 2.2.0 in manifest file

### ISSUE THREAD

**Issue by MTVExtreme** [cswendrowski/FoundryVTT-Drag-Upload#57]
![image](https://user-images.githubusercontent.com/5505510/190300127-db2dddf2-fa1a-4426-a93a-818193bdd2cc.png)

**Comment by Gawdl3y** [comment]
As a note, this is causing Foundry to infinitely "update" to version 2.2.0, never actually downloading 2.2.1.

**Comment by Keifeto** [comment]
This is still an ongoing issue

**Comment by throwaway-12345** [comment]
Temporary fix: forking the repo yourself, editing manifest.json (either via the github GUI or a text editor of your choise) to point to 2.2.1 and releasing manifest.json will probably work. 

An example release is here: https://github.com/throwaway-12345/FoundryVTT-Drag-Upload/releases/tag/test-release, and the link https://github.com/throwaway-12345/FoundryVTT-Drag-Upload/releases/download/test-release/module.json will be a valid json link for foundry. I would not use the above json link unless you trust me to not mess with the manifest, though.
