### ISSUE TITLE
When i enabled the module, i lose the capacity to drag and drop actor on my map from standard Actors Directory

### ISSUE THREAD

**Issue by p4535992** [cswendrowski/FoundryVTT-Drag-Upload#6]
Environment Details

Foundry VTT Version: 0.7.0
Operating System: [Windows]
How Are You Using Foundry: [Native Application (Electron), Chrome]
Which Game System: Dungeons and Dragons 5th Edition, version 0.94
Modules Enabled?: Yes

Description of the issue:

When i enabled the module, i lose the capacity to drag and drop actor on my map from standard Actors Directory.
No error on the web console.

**Comment by cswendrowski** [comment]
@p4535992 Thanks for bringing this to my attention - it looks like it was introduced in v1.2.0
v1.2.1 is now available with a fix
