### ISSUE TITLE
Feature Request - Add only the image wihtout create a Character or a npc

### ISSUE THREAD

**Issue by p4535992** [cswendrowski/FoundryVTT-Drag-Upload#7]
Sometime i don't want to create a Character or a NPC,  i just want to show a image.
It's possible on the form upload dialog to add the option for add for example a Journal Entry with the image or to put on the scene a tile with the background image set?

**Comment by cswendrowski** [comment]
@p4535992 not only is it possible, you can already do so! You'll want to go to the Journal Notes or Token layer

From the Readme:
```
If the file is an audio file (.mp3, .mp4, .wav, .flac), it will be created as an Ambient Audio with easing.

Otherwise, it will be treated as an Image and created based on the current active layer:

    Token: 1x1 Actor with Token
    Tile: Tile of the same size as the image
    Notes: Journal with a corresponding Journal Pin
    Other: Same as Token
```
