### ISSUE TITLE
[Issue] Module not Functioning

### ISSUE THREAD

**Issue by TheKillingJay** [cswendrowski/FoundryVTT-Drag-Upload#9]
Hello, your module has been working great until recently. It's been a lifesaver, but stopped functioning after I went to .66 and switched machines.

On a brand new 5e world with a fresh install of the module, this occurs

https://i.imgur.com/6jrkmHg.gif

I have absolutely no idea what is wrong with it. No error, no partial functionality, nothing. 

Thanks for your time.

**Comment by cswendrowski** [comment]
@TheKillingJay with help from the community, we have finally tracked this down - please do **not** run Foundry in admin mode - Windows blocks dragging files as a security feature when running the program as admin.
